config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  post '/assign' => 'tickets#assign'
  get '/forbidden' => 'static_pages#forbidden'
  get '/adminonly' => 'static_pages#admin'
  get '/my_tickets' => 'tickets#my_assigned_tickets', as: 'my_tickets'
  resources :users, only: %i[new create]
  resources :tickets do
    resources :comments
  end
  post '/tickets/assign' => 'tickets#assign'
  namespace :admin do
    resources :users
    post '/admin/promote' => 'users#promote'
    post '/admin/demote' => 'users#demote'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ticket

  validates :content, presence: true

  # def initialize(ticket:)
  #   @comment.ticket = ticket
  # end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :body, presence: true
  validates :title, presence: true

  scope :for, ->(user_id) do
    where(assigned_to: user_id)
  end

  delegate :email, to: :user, allow_nil: true, prefix: true
  delegate :email, to: :assigned_user, allow_nil: true, prefix: true

  def assigned_user
    User.find_by(id: self.assigned_to)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  has_many :tickets
  has_many :comments, through: :tickets

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  skip_before_action :verify_authenticity_token
  def index; end

  def promote
    @user = User.find(params[:user_id])
    @user.admin = true
    @user.save
    redirect_to admin_users_path
  end

  def demote
    @user = User.find(params[:user_id])
    @user.admin = false
    @user.save
    redirect_to admin_users_path
  end

  private

  def require_admin
    redirect_to adminonly_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def admin?
    current_user.admin
  end

  def require_login
    redirect_to forbidden_path  unless session.include? :user_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def new; end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to ticket_path(@comment.ticket)
    else
      render :show
    end
  end

  def show
    @comment ||= Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :ticket_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:user][:email])
    authenticated = user.try(:authenticate, params[:user][:password])
    binding.pry unless authenticated
    @user = user
    session[:user_id] = @user.id
    redirect_to tickets_path, notice: 'Thanks for signing in'
  end

  def destroy
    if session[:user_id]
      session[:user_id] = nil
      redirect_to root_path
    end
  end

  private

  def user_params
    params[:user]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.status = "new"
      if @ticket.save
        redirect_to ticket_path(@ticket.id)
      else
        render :new
      end
  end

  def my_assigned_tickets
    @tickets = Ticket.for(current_user)
    render :index
  end


  def index
    if admin?
      @tickets = Ticket.all
    else
      @tickets = Ticket.where("user_id = ?", current_user.id)
    end
  end

  def show
    @ticket ||= Ticket.find(params[:id])
    @comment = Comment.new
  end

  def assign
    @ticket = Ticket.find(params[:ticket_id])
    @ticket.assigned_to = current_user.id
    @ticket.save
    redirect_to ticket_path(@ticket)
  end
  private

  def ticket_params
    params.require(:ticket).permit(:title, :body, :due_date)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    current_user.admin == true
  end

  def form_errors_for(object = nil)
    render('shared/form_errors', object: object) unless object.blank?
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def assigned?(ticket)
    true if ticket.assigned_to != nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<% User.all.each do |user| %>
  <%= user.email %>
    <% if !user.admin? %>
      <%= form_tag("admin/promote", method: "post") do %>
      <%= hidden_field_tag(:user_id, "#{user.id}") %>
      <%= submit_tag("Promote to Admin") %>
      <% end %>
    <% elsif user.admin? %>
      <%= form_tag("admin/demote", method: "post") do %>
      <%= hidden_field_tag(:user_id, "#{user.id}") %>
      <%= submit_tag("Demote from Admin") %>
      <% end %>
  <% end %>
<% end %>
<br>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
<%= form_errors_for @comment %>
<%= f.hidden_field :ticket_id, value: @ticket.id %>
<%= f.label :content %>
<%= f.text_area :content %>

<%= f.submit %>
<% end %>

app/views/comments/show.html.erb
<div class="hidden-xs panel panel-default">
  <div class="panel-heading">
    <div>
      <strong>
        <h3 class="panel-title">Comment:</h3>
      </strong>
    </div>
  </div>
  <div class="panel-body">
    <div>
      <div class="body">
        <div>
          <p><%= @comment.content %></p>
        </div>
      </div>
      <strong>Comment by: <%= @comment.user.email %></strong><br>
    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Rails Support Tickets</title>
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i"/>
    <link rel="stylesheet" href="assets/css/untitled.css"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar">
      <div class="container">
        <a href="#" class="navbar-brand logo">Rails Support Tickets</a>
        <button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggler">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
          <ul class="nav navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li role="presentation"><%= link_to "Tickets", tickets_path, class: "nav-item nav-link active" %></a>
               <% if admin? %>
               <li role="presentation"><%= link_to "My Assigned Tickets", my_tickets_path, class: "nav-item nav-link active" %></a>
               <li role="presentation"><%= link_to "Admin Panel", admin_users_path, class: "nav-item nav-link active" %>
              <% end %>
            </li>
            <li role="presentation"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-item nav-link active" %></a></li>
          <% else %>
            <li role="presentation"><%= link_to "Login", new_user_session_path, class: "nav-item nav-link active" %></a>
          </li>
          <li role="presentation"><%= link_to "Signup", new_user_registration_path, class: "nav-item nav-link active" %></a>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</nav>
<main class="page">
<section class="clean-block" style="background-color:rgba(9, 162, 255, 0.85);">
  <div class="container clean-block">
    <br>
    <% if :form_errors %>
    <%= yield :form_errors %>
    <% end %>
    <%= yield %>
    <div class="block-heading"></div>
  </div>
</section>
</main>
<footer class="page-footer dark">
<div class="footer-copyright">
  <p>© 2018 Copyright Text</p>
</div>
</footer>
</body>

</html>

app/views/shared/_form_errors.html.erb
<% content_for :form_errors do %>
  <p>
    <% if object.errors.any? %>
    <%= pluralize(object.errors.count, "error") %> prevented the form from being saved:
  </p>
  <% end %>

  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/static_pages/admin.html.erb
<h1>FORBIDDEN</h1>
<br>
<h3>You must be an Admin to see this page</h3>
<p><%= link_to "I can take you home", root_path %></p>

app/views/static_pages/forbidden.html.erb
<h1>FORBIDDEN</h1>
<br>
<h3>You must be logged in to see this page</h3>
<p><%= link_to "I can take you home", root_path %></p>

app/views/static_pages/home.html.erb
<h1> Welcome to Rails Support Tickets. To get started please login or create an account</h1>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
<%= form_errors_for @ticket %>

  <%= f.label :title %><br>
  <%= f.text_field :title%><br>

  <%= f.label :body %><br>
  <%= f.text_area :body%><br>

  <%= f.label :due_date %><br>
  <%= f.text_field :due_date, "data-provide" => 'datepicker' %><br>

  <%= f.submit %>

<% end %>

app/views/tickets/_ticket.html.erb
<div class="hidden-xs panel panel-default">
  <div class="panel-heading">
    <div>
      <strong>
        <h3 class="panel-title">Ticket
          <%= ticket.id %>: <%= ticket.title %></h3>
      </strong>
    </div>
  </div>
  <div class="panel-body">
    <div>
      <div class="body">
        <div>
          <p><%= ticket.body %></p>
        </div>
      </div>
      <strong>Reported by:</strong><br> <%= ticket.user_email %>
    </div>
    <% if admin? && !assigned?(ticket) %>
      <%= form_tag("/assign", method: "post") do %>
      <%= hidden_field_tag(:ticket_id, "#{ticket.id}") %>
      <%= submit_tag("Assign Ticket to Me") %>
    <% end %>
  <% end %>
</div>
</div>

app/views/tickets/_ticket_index.html.erb
<%= @ticket.subject %>
<%= @ticket.body %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>
<a><%= link_to "Open a Support Ticket", new_ticket_path, style: 'float: right; color: black' %></a>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th width="5%">Ticket&nbsp;#</th>
      <th>Description</th>
      <th>Status</th>
      <th>Reported&nbsp;by</th>
      <th>Assigned&nbsp;to</th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td>
          <a><%= link_to "#{ticket.id}", ticket_path(ticket)%></a>
        </td>
        <td class="body">
          <p><%= "#{ticket.body}" %></p>
        </td>
        <td class="status">
          <div>
            <span><%= "#{ticket.status}" %></span>
          </div>
        </td>
        <td class="reported-by">
          <p><%= "#{ticket.user_email}" %></p>
        </td>
        <td class="assigned-to">
          <p><%= "#{ticket.assigned_user_email}" %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/new.html.erb
<h1></h1>
<%= render 'form' %>

app/views/tickets/show.html.erb
<%= render partial: "ticket", locals: {ticket:@ticket} %>
<br>
<% if @ticket.assigned_to.nil? %>
  <%= form_tag("/assign", method: "post") do %>
  <%= hidden_field_tag(:ticket_id, "#{@ticket.id}") %>
  <%= submit_tag("Assign to me") %>
   <% end %>
  <% else %>
  <div class="assigned_user">
    <strong>Assigned To:</strong>
    <p> <%= @ticket.assigned_user_email %> </p>
<% end %>

<% @ticket.comments.each do |comment| %>
<div class="comment">
  <strong><%= comment.user.email %></strong>
  <%= link_to "#{comment.content}", ticket_comment_path(@ticket, comment) %>
</div>
<% end %>

<h5>Comments:</h5>

<%= form_for [@ticket, @comment] do |f| %>

  <%= f.hidden_field :ticket_id, value: @ticket.id %>
  <%= f.text_area :content %><br>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<% if :form_errors %>
<%=  form_errors_for(@user) %>
<% end %>
<%= form_for @user, url: '/users', :html => {class: "center-block col-md-4", style:"float: none; background-color: grey"} do |f| %>
<%= form_errors_for @user %>
  Email: <%= f.text_field :email%>
  Password:<%= f.password_field :password, required: true %>
  Confirm Password: <%= f.password_field :password_confirmation, required: true %>
   <%= f.submit "Submit" %>
 <% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>